name: lgmoneda
markdown: kramdown
highlighter: rouge

t:
  en:
    home:
      name: "home"
      url: "/index-eng.html"
    blog:
      name: "blog"
      url: "/blog/"
    about:
      name: "about"
      url: "/about/"
    cv:
      name: "cv"
      url: "/cv/"
    projects:
      name: "projects"
      url: "/projects/"
    ds-course:
      name: "data science course"
      url: "/data-science-course/index.html"     
  fr:
    home:
      name: "Accueil"
      url: "/accueil/"
    about:
      name: "À propos"
      url: "/a-propos/"
    cv:
      name: "cv"
      url:  "/cv/"
  pt:
    home:
      name: "início"
      url: "/"
    blog:
      name: "blog"
      url: "/blog/index-pt.html"
    about:
      name: "sobre"
      url: "/about/index-pt.html"
    cv:
      name: "cv"
      url: "/cv/index-pt.html"
    projects:
      name: "projetos"
      url: "/projects/index-pt.html"
    ds-course:
      name: "curso de data science"
      url: "/data-science-course/index-pt.html"

gems: [rouge]
